/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_chen_desutil_Util */

#ifndef _Included_com_example_chen_desutil_Util
#define _Included_com_example_chen_desutil_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chen_desutil_Util
 * Method:    DESEncrypt
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chen_desutil_Util_DESEncrypt
  (JNIEnv *, jclass, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
